coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default: off
    patch:
      default: on
    changes:
      default: off

comment:
  layout: "diff, files"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "tasks/releasePullRequest.js"
  - "tasks/publish.js"
