export const allBounties = state => state.bounties.all
export const allCareers = state => state.careers.all
export const allMedia = state => state.media.all
export const people = state => state.people.all
export const allPresentations = state => state.presentations.all
export const ecosystem = state => state.ecosystem.data
export const config = state => state.config
export const links = state => state.links.data
export const issues = state => state.contribute.issues
