FROM circleci/golang:1.8.1-browsers

RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
RUN sudo apt-get install -y nodejs

RUN go get -d github.com/cosmos/cosmos-sdk
RUN cd $GOPATH/src/github.com/cosmos/cosmos-sdk && git checkout v0.7.1 && make get_vendor_deps && make install

RUN go get -d github.com/tendermint/tendermint/cmd/tendermint
RUN cd $GOPATH/src/github.com/tendermint/tendermint && git checkout v0.11.1 && make get_vendor_deps && make install

RUN sudo npm i -g yarn